/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devlink_server;

import java.util.concurrent.ExecutionException;

public class App {
    public static void main(String[] args) throws UnsupportedOperationException, InterruptedException, ExecutionException {
        FirebaseManager firebaseManager = new FirebaseManager();
        firebaseManager.InitializeFirebase();
        
    }
}
