/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devlink_server;

import java.util.concurrent.ExecutionException;

import devlink_server.StackExchangeManager.DataType;

public class App {
    public static void main(String[] args) throws UnsupportedOperationException, InterruptedException, ExecutionException {
        FirebaseManager firebaseManager = new FirebaseManager();
        firebaseManager.InitializeFirebase();
        int count = 0;
        while (true)
        {
            if (count == 0)
            {
                count++;
                System.out.println("Stuck in a loop!");
            }
        }
        // GitHubManager gitHubManager = new GitHubManager();
        // gitHubManager.Search(GitHubManager.DataType.User, "MHooijberg");
        // StackExchangeManager stackExchangeManager = new StackExchangeManager();
        // //stackExchangeManager.Search("Gson - how does it work?");
        // stackExchangeManager.Get(DataType.Question, "8523057");
    }
}
