/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devlink_server;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import java.util.*;
import java.lang.*;
import java.io.*;

public class App {
    public static void main(String[] args) {
        FirebaseManager firebaseManager;
        try {
            firebaseManager = new FirebaseManager();
            firebaseManager.InitializeFirebase();

            firebaseManager.FCMDirectExample("");
            firebaseManager.FCMMulticastExample(Arrays.asList("", ""));
            firebaseManager.FCMTopicExample("");
        } catch (Exception e) {
            // TODO: handle exception
        }
        

    }
}
